// Mocks generated by Mockito 5.4.5 from annotations
// in hiker_connect/test/trail_test/trail_list_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:hiker_connect/models/event_data.dart' as _i6;
import 'package:hiker_connect/models/event_filter.dart' as _i8;
import 'package:hiker_connect/models/trail_data.dart' as _i5;
import 'package:hiker_connect/services/databaseservice.dart' as _i3;
import 'package:hive/hive.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBox_0<E> extends _i1.SmartFake implements _i2.Box<E> {
  _FakeBox_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i3.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Box<_i5.TrailData>> getTrailBox() => (super.noSuchMethod(
        Invocation.method(
          #getTrailBox,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Box<_i5.TrailData>>.value(_FakeBox_0<_i5.TrailData>(
          this,
          Invocation.method(
            #getTrailBox,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Box<_i5.TrailData>>);

  @override
  _i4.Future<_i2.Box<_i6.EventData>> getEventBox() => (super.noSuchMethod(
        Invocation.method(
          #getEventBox,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Box<_i6.EventData>>.value(_FakeBox_0<_i6.EventData>(
          this,
          Invocation.method(
            #getEventBox,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Box<_i6.EventData>>);

  @override
  _i4.Future<_i2.Box<String>> getFavoritesBox() => (super.noSuchMethod(
        Invocation.method(
          #getFavoritesBox,
          [],
        ),
        returnValue: _i4.Future<_i2.Box<String>>.value(_FakeBox_0<String>(
          this,
          Invocation.method(
            #getFavoritesBox,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Box<String>>);

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> insertTrails(_i5.TrailData? trail) => (super.noSuchMethod(
        Invocation.method(
          #insertTrails,
          [trail],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.TrailData>> getTrails() => (super.noSuchMethod(
        Invocation.method(
          #getTrails,
          [],
        ),
        returnValue: _i4.Future<List<_i5.TrailData>>.value(<_i5.TrailData>[]),
      ) as _i4.Future<List<_i5.TrailData>>);

  @override
  _i4.Future<void> updateTrail(
    String? trailName,
    _i5.TrailData? trail,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTrail,
          [
            trailName,
            trail,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.TrailData?> getTrailByName(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrailByName,
          [name],
        ),
        returnValue: _i4.Future<_i5.TrailData?>.value(),
      ) as _i4.Future<_i5.TrailData?>);

  @override
  _i4.Future<void> syncTrailToFirestore(_i5.TrailData? trail) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncTrailToFirestore,
          [trail],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.TrailData>> getTrailsFromFirestore() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrailsFromFirestore,
          [],
        ),
        returnValue: _i4.Future<List<_i5.TrailData>>.value(<_i5.TrailData>[]),
      ) as _i4.Future<List<_i5.TrailData>>);

  @override
  _i4.Future<_i5.TrailData?> getTrailByNameFromFirestore(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrailByNameFromFirestore,
          [name],
        ),
        returnValue: _i4.Future<_i5.TrailData?>.value(),
      ) as _i4.Future<_i5.TrailData?>);

  @override
  _i4.Future<void> deleteTrail(int? trailId) => (super.noSuchMethod(
        Invocation.method(
          #deleteTrail,
          [trailId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTrailFromFirestore(int? trailId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTrailFromFirestore,
          [trailId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.EventData>> getAllEvents() => (super.noSuchMethod(
        Invocation.method(
          #getAllEvents,
          [],
        ),
        returnValue: _i4.Future<List<_i6.EventData>>.value(<_i6.EventData>[]),
      ) as _i4.Future<List<_i6.EventData>>);

  @override
  _i4.Future<String> createEvent(_i6.EventData? event) => (super.noSuchMethod(
        Invocation.method(
          #createEvent,
          [event],
        ),
        returnValue: _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #createEvent,
            [event],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<_i6.EventData?> getEvent(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #getEvent,
          [eventId],
        ),
        returnValue: _i4.Future<_i6.EventData?>.value(),
      ) as _i4.Future<_i6.EventData?>);

  @override
  _i4.Future<void> updateEvent(_i6.EventData? event) => (super.noSuchMethod(
        Invocation.method(
          #updateEvent,
          [event],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteEvent(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #deleteEvent,
          [eventId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<String>> getUserFavoriteEvents() => (super.noSuchMethod(
        Invocation.method(
          #getUserFavoriteEvents,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<void> addEventToFavorites(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #addEventToFavorites,
          [eventId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeEventFromFavorites(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeEventFromFavorites,
          [eventId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.EventData>> getEventsByFilter(_i8.EventFilter? filter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByFilter,
          [filter],
        ),
        returnValue: _i4.Future<List<_i6.EventData>>.value(<_i6.EventData>[]),
      ) as _i4.Future<List<_i6.EventData>>);
}
