// Mocks generated by Mockito 5.4.5 from annotations
// in hiker_connect/test/trail_test/trail_list_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:hiker_connect/models/trail_data.dart' as _i4;
import 'package:hiker_connect/services/databaseservice.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i2.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> insertTrails(_i4.TrailData? trail) => (super.noSuchMethod(
        Invocation.method(
          #insertTrails,
          [trail],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.TrailData>> getTrails() => (super.noSuchMethod(
        Invocation.method(
          #getTrails,
          [],
        ),
        returnValue: _i3.Future<List<_i4.TrailData>>.value(<_i4.TrailData>[]),
      ) as _i3.Future<List<_i4.TrailData>>);

  @override
  _i3.Future<void> updateTrail(
    String? trailName,
    _i4.TrailData? trail,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTrail,
          [
            trailName,
            trail,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.TrailData?> getTrailByName(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrailByName,
          [name],
        ),
        returnValue: _i3.Future<_i4.TrailData?>.value(),
      ) as _i3.Future<_i4.TrailData?>);

  @override
  _i3.Future<void> syncTrailToFirestore(_i4.TrailData? trail) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncTrailToFirestore,
          [trail],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.TrailData>> getTrailsFromFirestore() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrailsFromFirestore,
          [],
        ),
        returnValue: _i3.Future<List<_i4.TrailData>>.value(<_i4.TrailData>[]),
      ) as _i3.Future<List<_i4.TrailData>>);

  @override
  _i3.Future<_i4.TrailData?> getTrailByNameFromFirestore(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrailByNameFromFirestore,
          [name],
        ),
        returnValue: _i3.Future<_i4.TrailData?>.value(),
      ) as _i3.Future<_i4.TrailData?>);
}
